# Generated by Django 4.2.9 on 2026-02-18 16:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "credit_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated unique credit number",
                        max_length=20,
                        unique=True,
                        verbose_name="credit number",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("LIBRANZA", "Libranza (Payroll Deduction)"),
                            ("NATURAL", "Natural Person"),
                        ],
                        max_length=20,
                        verbose_name="credit type",
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount requested by customer in COP",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("100000.00")
                            )
                        ],
                        verbose_name="requested amount",
                    ),
                ),
                (
                    "requested_term",
                    models.PositiveIntegerField(
                        help_text="Requested term in months",
                        verbose_name="requested term",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount approved by credit approver in COP",
                        max_digits=12,
                        null=True,
                        verbose_name="approved amount",
                    ),
                ),
                (
                    "approved_term",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approved term in months",
                        null=True,
                        verbose_name="approved term",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                        verbose_name="annual interest rate",
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("BIWEEKLY", "Biweekly"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="payment frequency",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated monthly payment amount",
                        max_digits=12,
                        null=True,
                        verbose_name="monthly payment amount",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total amount including interest",
                        max_digits=12,
                        null=True,
                        verbose_name="total amount to pay",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="disbursement date"
                    ),
                ),
                (
                    "disbursement_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bank transfer, Cash, Check",
                        max_length=50,
                        verbose_name="disbursement method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("DISBURSED", "Disbursed"),
                            ("ACTIVE", "Active"),
                            ("PAID", "Paid Off"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current outstanding balance",
                        max_digits=12,
                        verbose_name="current balance",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approval date"
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(blank=True, verbose_name="approval notes"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "rejection_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="rejection date"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Purpose of the loan", verbose_name="loan purpose"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for libranza credits",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits",
                        to="customers.customer",
                        verbose_name="customer",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits_rejected",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="rejected by",
                    ),
                ),
                (
                    "sales_advisor",
                    models.ForeignKey(
                        help_text="User who created the credit application",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credits_as_advisor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="sales advisor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit",
                "verbose_name_plural": "credits",
                "db_table": "credits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["credit_number"], name="credits_credit__73a2af_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="credits_custome_d248ce_idx"
                    ),
                    models.Index(fields=["status"], name="credits_status_815afb_idx"),
                    models.Index(
                        fields=["credit_type"], name="credits_credit__3cd541_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="credits_created_c390c4_idx"
                    ),
                ],
            },
        ),
    ]
