# Generated by Django 4.2.9 on 2026-02-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_interestrateconfig_base_interest_rate"),
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="interest_rate",
        ),
        migrations.AddField(
            model_name="credit",
            name="aval_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Aval monthly rate used for calculation (7.05% or 4.05%)",
                max_digits=5,
                null=True,
                verbose_name="aval monthly rate",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="base_interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Base monthly interest rate % (e.g., 1.88 for 1.88%)",
                max_digits=5,
                null=True,
                verbose_name="base monthly interest rate",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="interest_rate_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Interest rate configuration used for this credit",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credits",
                to="core.interestrateconfig",
                verbose_name="interest rate configuration",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="iva_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="IVA percentage (e.g., 19.00 for 19%)",
                max_digits=5,
                null=True,
                verbose_name="IVA rate",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="monthly_aval",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly aval amount (difference between aval rate and base rate)",
                max_digits=12,
                null=True,
                verbose_name="monthly aval",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="monthly_iva_aval",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly IVA on aval (19% of aval)",
                max_digits=12,
                null=True,
                verbose_name="monthly IVA on aval",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="monthly_payment_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly payment with base interest only (capital + interest)",
                max_digits=12,
                null=True,
                verbose_name="monthly payment base",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="total_aval",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total aval (monthly_aval * term)",
                max_digits=12,
                null=True,
                verbose_name="total aval",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="total_interest",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total interest to pay",
                max_digits=12,
                null=True,
                verbose_name="total interest",
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="total_iva_aval",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total IVA on aval (monthly_iva_aval * term)",
                max_digits=12,
                null=True,
                verbose_name="total IVA on aval",
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current outstanding balance (only capital)",
                max_digits=12,
                verbose_name="current balance",
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="monthly_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total monthly payment (base + aval + IVA)",
                max_digits=12,
                null=True,
                verbose_name="total monthly payment",
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount to pay (monthly_payment * term)",
                max_digits=12,
                null=True,
                verbose_name="total amount to pay",
            ),
        ),
    ]
