# Generated by Django 4.2.9 on 2026-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credits", "0002_remove_credit_interest_rate_credit_aval_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DISBURSED", "Disbursed"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("DEFAULTED", "Defaulted"),
                    ("PAID_OFF", "Paid Off"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
