# Generated by Django 4.2.9 on 2026-02-18 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CEDULA", "Cédula de Ciudadanía"),
                            ("CEDULA_EXTRANJERIA", "Cédula de Extranjería"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        default="CEDULA",
                        max_length=20,
                        verbose_name="identification type",
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Identification number must contain only digits",
                                regex="^[0-9]+$",
                            )
                        ],
                        verbose_name="identification number",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Soltero/a"),
                            ("MARRIED", "Casado/a"),
                            ("DIVORCED", "Divorciado/a"),
                            ("WIDOWED", "Viudo/a"),
                            ("UNION", "Unión Libre"),
                        ],
                        default="SINGLE",
                        max_length=20,
                        verbose_name="marital status",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number must be valid",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="mobile number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="department/state"),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="neighborhood"
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        blank=True,
                        help_text="Employee code/number in the company",
                        max_length=50,
                        verbose_name="employee code",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="position/job title"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="hire date"),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly salary in COP",
                        max_digits=12,
                        verbose_name="monthly salary",
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        help_text="For self-employed or natural persons",
                        max_length=100,
                        verbose_name="occupation",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly income for natural persons in COP",
                        max_digits=12,
                        null=True,
                        verbose_name="monthly income",
                    ),
                ),
                (
                    "has_other_credits",
                    models.BooleanField(
                        default=False, verbose_name="has other credits"
                    ),
                ),
                (
                    "other_credits_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total other credits",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Company where the customer works (for libranza credits)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identification_number"],
                        name="customers_identif_9a9b54_idx",
                    ),
                    models.Index(
                        fields=["first_name", "last_name"],
                        name="customers_first_n_93c9ec_idx",
                    ),
                    models.Index(
                        fields=["company"], name="customers_company_df4bb6_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="customers_created_beab7c_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("company__isnull", False), ("employee_code__gt", "")
                ),
                fields=("company", "employee_code"),
                name="unique_employee_per_company",
            ),
        ),
    ]
