# Generated by Django 4.2.9 on 2026-02-18 14:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "nit",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NIT must contain only digits and hyphens",
                                regex="^[0-9\\-]+$",
                            )
                        ],
                        verbose_name="NIT",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="Legal business name (Razón Social)",
                        max_length=200,
                        verbose_name="business name",
                    ),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True,
                        help_text="Commercial name (Nombre Comercial)",
                        max_length=200,
                        verbose_name="trade name",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be valid",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("address", models.CharField(max_length=255, verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="department/state"),
                ),
                (
                    "agreement_number",
                    models.CharField(
                        help_text="Unique agreement/contract number",
                        max_length=50,
                        unique=True,
                        verbose_name="agreement number",
                    ),
                ),
                (
                    "agreement_date",
                    models.DateField(verbose_name="agreement start date"),
                ),
                (
                    "agreement_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for indefinite agreements",
                        null=True,
                        verbose_name="agreement end date",
                    ),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum loan amount per employee in COP",
                        max_digits=12,
                        verbose_name="maximum loan amount per employee",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage (e.g., 24.50)",
                        max_digits=5,
                        verbose_name="annual interest rate",
                    ),
                ),
                (
                    "max_term_months",
                    models.PositiveIntegerField(
                        default=36,
                        help_text="Maximum loan term in months",
                        verbose_name="maximum term in months",
                    ),
                ),
                (
                    "max_deduction_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Maximum percentage of salary that can be deducted (e.g., 50.00)",
                        max_digits=5,
                        verbose_name="maximum payroll deduction percentage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("SUSPENDED", "Suspendido"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "contact_person_name",
                    models.CharField(
                        max_length=200, verbose_name="contact person name"
                    ),
                ),
                (
                    "contact_person_position",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="contact person position",
                    ),
                ),
                (
                    "contact_person_phone",
                    models.CharField(
                        max_length=15, verbose_name="contact person phone"
                    ),
                ),
                (
                    "contact_person_email",
                    models.EmailField(
                        max_length=254, verbose_name="contact person email"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "db_table": "companies",
                "ordering": ["business_name"],
                "indexes": [
                    models.Index(fields=["nit"], name="companies_nit_9596c6_idx"),
                    models.Index(
                        fields=["business_name"], name="companies_busines_7c0229_idx"
                    ),
                    models.Index(fields=["status"], name="companies_status_2cde5e_idx"),
                    models.Index(
                        fields=["agreement_number"], name="companies_agreeme_b5d40a_idx"
                    ),
                ],
            },
        ),
    ]
