# Generated by Django 4.2.9 on 2026-02-20 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="payment_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Day of the month when the company pays salaries (1-31). Used for Libranza credits.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="payment day",
            ),
        ),
    ]
