# Generated by Django 4.2.9 on 2026-02-20 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_payment_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="company",
            name="max_deduction_percentage",
        ),
        migrations.RemoveField(
            model_name="company",
            name="max_loan_amount",
        ),
        migrations.RemoveField(
            model_name="company",
            name="max_term_months",
        ),
    ]
