# Generated by Django 4.2.9 on 2026-02-18 16:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestRateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="Year (e.g., 2026)", verbose_name="year"
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        help_text="Month (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="month",
                    ),
                ),
                (
                    "usury_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual usury rate percentage (e.g., 25.01 for 25.01%)",
                        max_digits=5,
                        verbose_name="usury rate",
                    ),
                ),
                (
                    "base_interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Calculated monthly base interest rate (e.g., 1.88 for 1.88%)",
                        max_digits=5,
                        verbose_name="base interest rate",
                    ),
                ),
                (
                    "aval_rate_libranza",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("7.05"),
                        help_text="Aval monthly rate for payroll deduction credits",
                        max_digits=5,
                        verbose_name="aval rate - libranza",
                    ),
                ),
                (
                    "aval_rate_high",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("4.05"),
                        help_text="Aval monthly rate for credits > 5M",
                        max_digits=5,
                        verbose_name="aval rate - high amount",
                    ),
                ),
                (
                    "aval_rate_low",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("7.05"),
                        help_text="Aval monthly rate for credits <= 5M",
                        max_digits=5,
                        verbose_name="aval rate - low amount",
                    ),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19.00"),
                        help_text="IVA percentage",
                        max_digits=5,
                        verbose_name="IVA rate",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rate is currently active",
                        verbose_name="active",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this rate becomes effective",
                        verbose_name="effective date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interest_rates_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "interest rate configuration",
                "verbose_name_plural": "interest rate configurations",
                "db_table": "interest_rate_configs",
                "ordering": ["-year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="interest_ra_year_09c465_idx"
                    ),
                    models.Index(
                        fields=["effective_date"], name="interest_ra_effecti_d061d0_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="interest_ra_is_acti_9666f0_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="interestrateconfig",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="unique_rate_per_month"
            ),
        ),
    ]
