# Generated by Django 4.2.9 on 2026-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestrateconfig",
            name="base_interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Calculated monthly base interest rate (e.g., 1.88 for 1.88%)",
                max_digits=5,
                null=True,
                verbose_name="base interest rate",
            ),
        ),
    ]
