# Generated by Django 4.2.9 on 2026-02-24 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_interestrateconfig_base_interest_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="interestrateconfig",
            name="late_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.89"),
                help_text="Monthly late payment interest rate (e.g., 3.00 for 3%)",
                max_digits=5,
                verbose_name="late interest rate",
            ),
        ),
    ]
