# Generated by Django 4.2.9 on 2026-02-18 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credits", "0002_remove_credit_interest_rate_credit_aval_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "payment_number",
                    models.PositiveIntegerField(
                        help_text="Sequential payment number (1, 2, 3...)",
                        verbose_name="payment number",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date when payment is due",
                        verbose_name="due date",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual date when payment was made",
                        null=True,
                        verbose_name="payment date",
                    ),
                ),
                (
                    "scheduled_capital",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scheduled capital portion for this payment",
                        max_digits=12,
                        verbose_name="scheduled capital",
                    ),
                ),
                (
                    "scheduled_interest",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scheduled interest portion for this payment",
                        max_digits=12,
                        verbose_name="scheduled interest",
                    ),
                ),
                (
                    "scheduled_aval",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scheduled aval portion for this payment",
                        max_digits=12,
                        verbose_name="scheduled aval",
                    ),
                ),
                (
                    "scheduled_iva_aval",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Scheduled IVA on aval for this payment",
                        max_digits=12,
                        verbose_name="scheduled IVA on aval",
                    ),
                ),
                (
                    "scheduled_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total scheduled payment amount",
                        max_digits=12,
                        verbose_name="scheduled total",
                    ),
                ),
                (
                    "paid_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual capital paid",
                        max_digits=12,
                        verbose_name="paid capital",
                    ),
                ),
                (
                    "paid_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual interest paid",
                        max_digits=12,
                        verbose_name="paid interest",
                    ),
                ),
                (
                    "paid_aval",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual aval paid",
                        max_digits=12,
                        verbose_name="paid aval",
                    ),
                ),
                (
                    "paid_iva_aval",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual IVA on aval paid",
                        max_digits=12,
                        verbose_name="paid IVA on aval",
                    ),
                ),
                (
                    "paid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount actually paid",
                        max_digits=12,
                        verbose_name="paid total",
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Late payment fee charged",
                        max_digits=12,
                        verbose_name="late fee",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Outstanding balance before this payment",
                        max_digits=12,
                        verbose_name="balance before payment",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Outstanding balance after this payment",
                        max_digits=12,
                        null=True,
                        verbose_name="balance after payment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("LATE", "Late"),
                            ("PARTIAL", "Partially Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Bank transfer, Cash, Card, Payroll deduction",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank reference or transaction ID",
                        max_length=100,
                        verbose_name="transaction reference",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="credits.credit",
                        verbose_name="credit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "db_table": "payments",
                "ordering": ["credit", "payment_number"],
                "indexes": [
                    models.Index(
                        fields=["credit", "payment_number"],
                        name="payments_credit__4b97b3_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="payments_due_dat_ff319d_idx"
                    ),
                    models.Index(fields=["status"], name="payments_status_d621e5_idx"),
                    models.Index(
                        fields=["payment_date"], name="payments_payment_aebcb7_idx"
                    ),
                ],
                "unique_together": {("credit", "payment_number")},
            },
        ),
    ]
