# Generated by Django 4.2.9 on 2026-02-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_deadline",
            field=models.DateField(
                blank=True,
                help_text="Final deadline for payment. For Libranza: company payment day. For others: same as due_date.",
                null=True,
                verbose_name="payment deadline",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="period_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of days in this payment period",
                null=True,
                verbose_name="period days",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(
                db_index=True,
                help_text="Date when payment is due (end of month)",
                verbose_name="due date",
            ),
        ),
    ]
