# Generated by Django 4.2.9 on 2026-02-24 13:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0002_payment_payment_deadline_payment_period_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date when payment was received",
                        verbose_name="transaction date",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount received in this transaction",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CARD", "Card"),
                            ("PSE", "PSE"),
                            ("CHECK", "Check"),
                            ("PAYROLL_DEDUCTION", "Payroll Deduction"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction reference (e.g., transfer number, check number)",
                        max_length=100,
                        verbose_name="reference number",
                    ),
                ),
                (
                    "applied_to_late_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="applied to late interest",
                    ),
                ),
                (
                    "applied_to_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="applied to interest",
                    ),
                ),
                (
                    "applied_to_aval",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="applied to aval",
                    ),
                ),
                (
                    "applied_to_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="applied to IVA",
                    ),
                ),
                (
                    "applied_to_capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="applied to capital",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "payment transaction",
                "verbose_name_plural": "payment transactions",
                "db_table": "payment_transactions",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="balance_after",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="late_fee",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_reference",
        ),
        migrations.AddField(
            model_name="payment",
            name="applied_late_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Late interest that has been applied to this payment",
                max_digits=12,
                verbose_name="applied late interest",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="calculated_late_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Calculated but not yet applied late interest",
                max_digits=12,
                verbose_name="calculated late interest",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="late_interest_applied_date",
            field=models.DateField(
                blank=True,
                help_text="Date when late interest was applied",
                null=True,
                verbose_name="late interest applied date",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="late_interest_calculated_date",
            field=models.DateField(
                blank=True,
                help_text="Last date when late interest was calculated",
                null=True,
                verbose_name="late interest calculation date",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="late_interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Monthly late interest rate (e.g., 3.00 for 3%)",
                max_digits=5,
                verbose_name="late interest rate",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_late_interest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Actual late interest paid",
                max_digits=12,
                verbose_name="paid late interest",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_deadline"], name="payments_payment_e9b7e6_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="payments.payment",
                verbose_name="payment",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment", "-transaction_date"],
                name="payment_tra_payment_90c2ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["transaction_date"], name="payment_tra_transac_20dbca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_method"], name="payment_tra_payment_45950f_idx"
            ),
        ),
    ]
